use_frameworks!

target 'RIRImageResizing_Example' do
  pod 'RIRImageResizing', :path => '../'

  target 'RIRImageResizing_Tests' do
    inherit! :search_paths
	
	pod 'RTSMTableSectionManager', '0.1.8'
	pod 'ResplendentUtilities', '0.5.0'
  end
end
