use_frameworks!

target 'RIRImageResizing_Example' do
  pod 'RIRImageResizing', :path => '../'
  pod 'RTSMTableSectionManager'

  target 'RIRImageResizing_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
